print(" Give me a noun. ")
noun1=input()
print(" Give me another noun. ")
noun2=input()
print(" Give me a verb. ")
verb1=input()
print(" Give me another verb. ")
verb2=input()
print(" Give me a place.")
place=input()
print(" Give me an adjective. ")
adjective1=input()
print(" Give me an adjective. ")
adjective2=input()
print(adjective1 + " " + noun1 + " " + "and" + " " + adjective2 + " " + noun2 + " " + verb1 + " " + "and" + " " + verb2 + " while they were at" + " " + place + ".")
